name: myapp
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: "3.7.0-209.1.beta" # Usa una versione stabile di Dart

dependencies:
  flutter:
    sdk: flutter
  http : ^1.1.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/attractions.json